// vuetodo/src/App.vue
<script setup lang="ts">
  import { ref, watchEffect } from 'vue';
  import Header from './components/Header.vue'
  import Todo from './components/Todo.vue'

  export type Todo = {
    id: number
    title: string
    description: string
    isCompleted: boolean
  }

  let titleInput = ref("")  
  let descInput = ref("")

  const existingTodos = localStorage.getItem("todos")
  const _todos = existingTodos ? JSON.parse(existingTodos) : []
  const todos = ref<Todo[]>(_todos)

  watchEffect(() => localStorage.setItem("todos", JSON.stringify(todos.value)))

  const addTodo = () => {
    todos.value = [
      ...todos.value,
      { id: Math.random(), title: titleInput.value, description: descInput.value, isCompleted: false }
    ]
    titleInput.value = ""
    descInput.value = ""
  }

  const updateTodo = (id: number) => (title: string, description: string) => {
    todos.value = todos.value.map(todo => todo.id === id ?
      { ...todo, title, description } :
      todo)
  }

  const deleteOne = (id: number) => {
    todos.value = todos.value.filter(todo => todo.id !== id)
  }

  const deleteAll = () => {
    todos.value = []
  }
</script>

<template>
  <main class="max-w-[800px] m-auto min-h-screen bg-gray-400">
    <Header>My todo app</Header>
  
    <div class="border-2 rounded-md p-4 border-gray-800 flex flex-col items-center gap-4 max-w-[400px] m-auto">
      <input class="p-2" placeholder="Title" type="text" v-model="titleInput">
      <input class="p-2" placeholder="Description" type="text" v-model="descInput">
      <button class="rounded-md border-2 bg-gray-900 text-white p-2" @click="addTodo">Add todo</button>
    </div>
    
    <hr class="my-4">
    
    <button class="rounded-md border-2 bg-gray-900 text-white p-2 m-auto block" @click="deleteAll">Delete all</button>
  
    <hr class="my-4">
  
    <Header>Todos</Header>
  
    <div v-for="todo in todos" class="flex flex-wrap gap-4 m-4">
      <Todo
        :todo="todo"
        :onDelete="() => deleteOne(todo.id)"
        :onUpdate="updateTodo(todo.id)" />
    </div>
  </main>
</template>

<style scoped>
</style>

// reacttodo/src/App.tsx
import { useEffect, useState } from 'react'
import Header from './components/Header'
import { TodoRender } from './components/TodoRender'

export type Todo = {
    id: number
    title: string
    description: string
    isCompleted: boolean
}

function App(){

    const [titleInput, setTitleInput] = useState("")
    const [descInput, setDescInput] = useState("")
    
    const existingTodos = localStorage.getItem("todos")
    const _todos = existingTodos ? JSON.parse(existingTodos) : []
    const [todos, setTodos] = useState<Todo[]>(_todos)

    useEffect(() => localStorage.setItem("todos", JSON.stringify(todos)))

    const addTodo = () => {
        const newTodo: Todo = {
            id: Math.random(),
            title: titleInput,
            description: descInput,
            isCompleted: false
        }
        setTodos([...todos, newTodo])
        setTitleInput("")
        setDescInput("")
    }

    const updateTodo = (id: number) => (title: string, description: string) => {
        setTodos(todos.map(todo => todo.id === id ? {...todo, title, description} : todo))
    }

    const deleteOne = (id: number) => {
        setTodos(todos.filter(todo => todo.id !== id))
    }

    const deleteAll = () => {
        setTodos([])
    }

    return(
        <main className="max-w-[800px] m-auto min-h-screen bg-gray-400">
            <Header title="My todo app"/>

            <div className="border-2 rounded-md p-4 border-gray-800 flex flex-col items-center gap-4 max-w-[400px] m-auto">
                <input className="p-2" placeholder='Title' type="text" value={titleInput} onChange={(e) => setTitleInput(e.target.value)}/>
                <input className="p-2" placeholder='Description' type="text" value={descInput} onChange={(e) => setDescInput(e.target.value)}/>
                <button className="rounded-md border-2 bg-gray-900 text-white p-2" onClick={addTodo}>Add todo</button>
            </div>

            <hr className="my-4"/>

            <button className="rounded-md border-2 bg-gray-900 text-white p-2 m-auto block" onClick={deleteAll}>Delete all</button>
        
            <hr className="my-4"/>

            <Header title="Todos"/>

            <div  className="flex flex-wrap gap-4 m-4">
                {todos.map(todo => 
                <TodoRender 
                    todo={todo}
                    onDelete={ () => deleteOne(todo.id) }
                    onUpdate={ updateTodo(todo.id) } 
                />)}
            </div>

        </main>
    )
}

export default App
